config-version: 2

name: "dbt_cloud_demo"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 398803 # Put your project id here

profile: astrafy # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Europe/Paris"

seeds:
  +tags: dbt_cloud_demo
  dbt_cloud_demo:
    +schema: raw

models:
  +tags: dbt_cloud_demo
  dbt_cloud_demo:
    staging:
      +materialized: table
    datamart:
      +materialized: table
